# Generated by Django 3.2.4 on 2021-08-23 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='date',
        ),
    ]
